### ISSUE TITLE
TopPage実装

### ISSUE THREAD

**Issue by Yuma-Satake** [Yuma-Satake/My-Shienkin-Navi#3]
## 実装箇所
`src/pages/TopPage.tsx`

## 実装用件
支援金検索と個人データ共有・受取へ遷移するページの実装
- 支援金検索のカードをクリックすると`SupportSearchPage`へ遷移
- 個人データの共有・受取のカードをクリックすると`DataTopPage`へ遷移

## イメージ Figma
<img width="300px" src="https://github.com/Yuma-Satake/My-Shienkin-Navi/assets/109256327/9d00391b-7dbf-4893-9df5-e853a39fc150">

**Comment by KHashimoto3** [comment]
SupportSearchPageとかDataTopPageへの遷移って、どう実現するほうがいいですかね？
データを渡すわけではないので、react-routerのpush関数使って遷移させる形でいいですか？

**Comment by Yuma-Satake** [comment]
> SupportSearchPageとかDataTopPageへの遷移って、どう実現するほうがいいですかね？
> データを渡すわけではないので、react-routerのpush関数使って遷移させる形でいいですか？

認識に相違ありません！
適宜pushとnavigateを使い分ける形で問題ないと思います🙆

**Comment by KHashimoto3** [comment]
ありがとうございます！その様にします！
react-router初心者で初歩的なことを聞いてしまうかもしれないですがよろしくお願いします🙇

**Comment by KHashimoto3** [comment]
遷移先の、SupportSearchPageと、DataTopPageはまだないのですが、
こちらで仮（pタグの文章だけのやつ）で作ってしまってもいい感じですか？
それともページがない状態で、React-routerの設定書いてしまっていいですか？

**Comment by Yuma-Satake** [comment]
LGTM💪
