### ISSUE TITLE
ロード画面の実装

### ISSUE THREAD

**Issue by mochi-yu** [Yuma-Satake/My-Shienkin-Navi#43]
## 実装箇所

``src\components```

## 実装用件

- [ ] API接続時などに処理が終わるまでロード画面を表示する

## イメージ Figma
**作成中**
<img width="300px" src="">

**Comment by yukiharada1228** [comment]
ひとまず，簡単なロード画面を作成しました．
より具体的なイメージはFigmaで一緒に考えていただけると助かります．

*gifに変換したためフレームレートが実際と違います．
<img src=https://github.com/Yuma-Satake/My-Shienkin-Navi/assets/117978472/c20bd416-9a68-4916-a51c-6839df928464 width=300 />
