### ISSUE TITLE
マイナポータルからのデータ取得に関するページの実装

### ISSUE THREAD

**Issue by mochi-yu** [Yuma-Satake/My-Shienkin-Navi#49]
## 実装箇所

``

## 実装用件

- [ ] 本人同意と本人確認のページ
- [ ] 利用者証明用電子証明書パスワードの入力画面
- [ ] 情報提供可否の確認画面
- [ ] データ取得完了画面

## イメージ （ダミー環境のスクリーンショット）

<img width="300px" src="https://github.com/Yuma-Satake/My-Shienkin-Navi/assets/43375000/17f69bdb-9968-4da8-863e-af09fd2eba56">
<img width="300px" src="https://github.com/Yuma-Satake/My-Shienkin-Navi/assets/43375000/a8081b5b-4828-4c50-ab47-bcf1c2ecfb62">
<img width="300px" src="https://github.com/Yuma-Satake/My-Shienkin-Navi/assets/43375000/342ee537-78c1-4a48-b673-62e2b8f25529">
<img width="300px" src="https://github.com/Yuma-Satake/My-Shienkin-Navi/assets/43375000/c12be1e2-f49c-42ad-a6fb-99b9ea0bdf12">

**Comment by yukiharada1228** [comment]
@mochi-yu 
全部で4画面ありますが，1ページ1ファイルで実装したいと思います．
実装箇所など指定があれば教えていただけると幸いです．
