### ISSUE TITLE
DataTopPage実装

### ISSUE THREAD

**Issue by Yuma-Satake** [Yuma-Satake/My-Shienkin-Navi#5]
## 実装箇所

`src/pages/DataTopPage.tsx`

## 実装用件

データの共有・受取画面へ遷移するトップページの作成
- `データを共有する`をクリックして`DataSharePage`へ遷移
- `共有されたデータを受け取る`をクリックして`DataReceivePage`へ遷移
- `最初の画面へ戻る`をクリックして`TopPage`へ遷移
- `データ共有についての説明を見る`の動作に関しては保留
- 画像に関しては https://loosedrawing.com から、色をテーマカラーと合わせて選択

## イメージ Figma

<img width="300px" src="https://github.com/Yuma-Satake/My-Shienkin-Navi/assets/109256327/a70dd15a-4e68-4647-9ae6-f88e4f0e28bd" >

**Comment by uedamasanari** [comment]
こちら明日から始めます〜
