### ISSUE TITLE
SupportSearchPage実装

### ISSUE THREAD

**Issue by Yuma-Satake** [Yuma-Satake/My-Shienkin-Navi#6]
## 実装箇所

`src/pages/SupportSearchPage.tsx`

## 実装用件
支援金の検索をするページの実装
- おすすめ欄の下に支援金の適当なモックデータを表示（dataディレクトリ下に配置）
  - カードをクリックで`SupportDetailPage`へ遷移
- 種類から探す欄には5つ程度の支援金の種類（奨学金・給付金等）を表示（dataディレクトリに配置）
  - ボタンをクリックで`SupportListPage`へ遷移

## イメージ Figma

<img width="300px" src="https://github.com/Yuma-Satake/My-Shienkin-Navi/assets/109256327/1c61d53a-53b7-44ad-bb08-d2342ec30d51">

**Comment by yukiharada1228** [comment]
Keyの設定がされておらず，エラーが発生していた
<img width="342" alt="image" src="https://github.com/Yuma-Satake/My-Shienkin-Navi/assets/117978472/9ddb16d1-89e8-4354-ba9a-fcde4500bc5c">
