### ISSUE TITLE
SupportDetailPage実装

### ISSUE THREAD

**Issue by Yuma-Satake** [Yuma-Satake/My-Shienkin-Navi#8]
## 実装箇所

`src/pages/SupportDetailPage.tsx`

## 実装用件
支援金・給付金の詳細を表示するページの実装
- いい感じのイラストをお願いします。
- 各項目に関しては一旦固定表示（dataディレクトリ下に配置）
- `この支援金を申請する`ボタンは非動作
- `支援金の選択に戻る`クリックで`SupportListPage`へ遷移

## イメージ Figma

<img width="300px" src="https://github.com/Yuma-Satake/My-Shienkin-Navi/assets/109256327/e815f336-a532-482a-87a4-0dd699ab1d06">

**Comment by yukiharada1228** [comment]
@Yuma-Satake 
お疲れ様です．なかなか実装に加わることができず申し訳ないです．
ひとまず，大体の機能は実装できました．
アドバイスいただけると嬉しいです．
typescriptがよくわからないので，ひとまずjavascriptで書いているつもりです．
よろしくお願いいたします．

**Comment by yukiharada1228** [comment]
<img width="293" alt="スクリーンショット 2023-05-21 19 10 27" src="https://github.com/Yuma-Satake/My-Shienkin-Navi/assets/117978472/eb6e5007-6511-493f-b5ad-7d4652a3bf63">
スクショです．
